name: Deploy a bundle including a Grype database

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: buildpacks/github-actions/setup-pack@v5.2.0
    - uses: anchore/scan-action/download-grype@v3
    - name: Log in to the container registry
      uses: docker/login-action@v2
      with:
        registry: quay.io/armosec
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and deploy image
      run: make install
